name: Generate Snake Animation

on:
  # Run workflow every 6 hours
  schedule:
    - cron: "0 */6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run workflow each time a commit is pushed to your repository
  push:
    branches:
      - main

  # Run workflow on the first pull request targeting the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Download the Snake animation code
      - name: Checkout repository content
        uses: actions/checkout@v2

      # Generate the Snake animation
      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: MohamedBarbych
          outputs: dist/snake.svg

      # Push the Snake animation to the output branch
      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
